file_path = 'data/train_data.csv'
K_RANGE = (2, 5)
K2_RANGE = range(2, 5)
K_PROTOTYPE_RANGE = range(2, 10)
N_INIT = 10
MAX_ITER = 100
INIT = 'k-means++'
CONTAMINATION = 0.001
RANDOM_STATE = 123
N_COMPONENTS = 3
PCA_N_ITER = 3
MCA_N_ITER = 100
TSNE_LEARNING_RATE = 500
TSNE_PERPLEXITY = 200
TSNE_N_ITER = 5000
SAMPLING_FRACTION = 0.01
KPROTOTYPE_INIT = 'Huang'
GAMMA = 2.55  #lower gamma give more priority to numerical culomns. Higher gamma give more priority to categorigal columns